apiVersion: v1
kind: Service
metadata:
  name: ai-agent-api
  labels:
    app: ai-agent-api
spec:
  type: ClusterIP
  selector:
    app: ai-agent-api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent-api
  labels:
    app: ai-agent-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent-api
  template:
    metadata:
      labels:
        app: ai-agent-api
    spec:
      containers:
        - name: api
          image: jackyang01/ai-agent-api:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: MODEL_PATH
              value: /models/ai_agent_model/llama_3_2_tuned_agent
            - name: PYTHONUNBUFFERED
              value: "1"
          envFrom:
            - secretRef:
                name: slm-secret
          volumeMounts:
            - name: model-storage
              mountPath: /models
              readOnly: true

          startupProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
            failureThreshold: 60
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 20
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
            requests:
              cpu: "2"
              memory: "6Gi"
            limits:
              cpu: "4"
              memory: "10Gi"
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: my-pvc-slm-models
