# Job template (Deterministic fine-tuning job)
apiVersion: batch/v1
kind: Job
metadata:
  name: train-job
  namespace: default
  labels:
    app: slm-fine-tune
spec:
  template:
    metadata:
      labels:
        app: slm-fine-tune
    spec:
      # --- Pod Runtime Configuration ---
      restartPolicy: OnFailure      # Must be 'Never' or 'OnFailure' for Jobs
      containers:
        - name: worker
          image: jackyang01/slm-jobs:latest
          imagePullPolicy: Always
          command: ["python3", "fine-tune.py", "--dataset_location", "qa_training.txt", "--model_storage_location", "/models/test"]

          envFrom:
            - secretRef:
                name: slm-secret
            - configMapRef:
                name: slm-configmap

          env:
            - name: PYTHONUNBUFFERED # For debug purposes, real-time logging output to "kubectl logs"
              value: "1"

          volumeMounts:
            - name: model-storage
              mountPath: /models

          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
            requests:
              cpu: "500m"
              memory: "2Gi"

      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: my-pvc-slm-models
