apiVersion: batch/v1
kind: Job
metadata:
  name: train-job
  namespace: default
  labels:
    app: slm-fine-tune
spec:
# --- Job Behavior Configuration ---
  # backoffLimit: 4               # Number of retries before marking the job as failed
  # activeDeadlineSeconds: 600    # Maximum duration the job can run (10 minutes)
  # completions: 1                # Total number of successful pods required to finish
  # parallelism: 1                # Number of pods allowed to run concurrently
  # ttlSecondsAfterFinished: 100  # Automatically cleans up/deletes the job after it ends

  template:
    metadata:
      labels:
        app: slm-fine-tune
    spec:
      # --- Pod Runtime Configuration ---
      restartPolicy: OnFailure      # Must be 'Never' or 'OnFailure' for Jobs
      containers:
        - name: worker
          image: jackyang01/slm-jobs:latest
          imagePullPolicy: Always
          command: ["python3", "fine-tune.py", "--dataset_location", "qa_training.txt", "--model_storage_location", "/models/test"]

          envFrom:
            - secretRef:
                name: slm-secret
            - configMapRef:
                name: slm-configmap

          env:
            - name: PYTHONUNBUFFERED
              value: "1"

          volumeMounts:
            - name: model-storage
              mountPath: /models

          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
            requests:
              cpu: "500m"
              memory: "2Gi"

      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: my-pvc-slm-models
