# Service account associated with job submitter APP 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: slm-job-submitter
  namespace: default

---
# Role-Based Access Control (Specify the permission as needed)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: slm-job-submitter
  namespace: default
rules:
  - apiGroups: # Batch group
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
  - apiGroups:
      - ""
    resources: # Default group 
      - pods 
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get

---
# Role Binding (like IAM role to user)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: slm-job-submitter
  namespace: default
subjects:
  - kind: ServiceAccount
    name: slm-job-submitter
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: slm-job-submitter
