# PostgreSQL Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-slm-db
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce # Only one Pod can use this at a time
  persistentVolumeReclaimPolicy: Retain # Keep the data even if the PVC is deleted
  storageClassName: manual
  # For demo ONLY - DO NOT USE IN PRODUCTION
  hostPath:
    path: /mnt/slm-postgres
    type: DirectoryOrCreate

---
# PostgreSQL Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-slm-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi

---
# Model Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-slm-models
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  # For demo ONLY - DO NOT USE IN PRODUCTION
  hostPath:
    path: /mnt/slm-models
    type: DirectoryOrCreate

---
# Model Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-slm-models
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
