# PostgreSQL Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # Only one Pod can use this at a time
  persistentVolumeReclaimPolicy: Retain # Keep the data even if the PVC is deleted
  storageClassName: manual
  # For demo ONLY - DO NOT USE IN PRODUCTION
  hostPath:
    path: /mnt/test-db
    type: DirectoryOrCreate

---
# PostgreSQL Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-db-configmap
data:
  DB_PORT: "5432"

---
apiVersion: v1
kind: Secret
metadata:
  name: test-db-secret
type: Opaque
stringData:
  POSTGRES_DB: testdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

---
# DATABASE SERVICE
apiVersion: v1
kind: Service
metadata:
  name: test-db-service
  labels:
    app: test-db
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: test-db

---
# STATEFUL SET
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-db-statefulset
  labels:
    app: test-db
spec:
  serviceName: test-db-service
  replicas: 1
  selector:
    matchLabels:
      app: test-db
  template:
    metadata:
      labels:
        app: test-db
    spec:
      containers:
        - name: test-db
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - configMapRef:
                name: test-db-configmap
            - secretRef:
                name: test-db-secret
          volumeMounts:
            - name: my-test-db-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: my-test-db-volume 
          persistentVolumeClaim:
            claimName: test-db-pvc
