apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ml-app
  labels:
    app: ml-app
spec:
  serviceName: ml-service
  replicas: 1
  selector:
    matchLabels:
      app: ml-app
  template:
    metadata:
      labels:
        app: ml-app
    spec:
      containers:
        - name: ml-app
          image: jackyang01/ml-pipeline:latest
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args: ["echo 'model registry pod running'; sleep infinity"]
          # command: ["sh", "-c", "while true; do echo 'Hello from my-pod!' >> /data/my-file.txt; sleep 5; done"]
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: ml-secret
          volumeMounts:
            - name: my-volume-ml
              mountPath: /models
      volumes:
        - name: my-volume-ml # This name MUST match the volumeMount name
          persistentVolumeClaim:
            claimName: my-pvc-ml # This must match the PVC name
